name: Build

on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+\.*'
  pull_request:
    branches:
      - master
      - develop
      - 'v[0-9]+.[0-9]+'

env:
  CARGO_TERM_COLOR: always

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Default build
        run: cargo check --workspace
  features:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        feature:
          - alloc
          - std
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Feature ${{ matrix.feature }}
        run: cargo check --no-default-features --features=${{ matrix.feature }}
      - name: Defaults + ${{ matrix.feature }}
        run: cargo check --features=${{ matrix.feature }}
  platforms:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04, macos-12, macos-13, windows-2019, windows-2022 ]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build with all features
        run: cargo check --workspace --all-targets --all-features
  toolchains:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [ nightly, beta, stable, 1.75.0 ]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: All features
        run: cargo check --workspace --all-targets --all-features
